import type { Access, CollectionConfig } from 'payload'

import { editorOnly, isStaff } from '../access'

/** 公開済みのみ read（補-8-8-3）。下書きは公開 API に出さない */
const readPublished: Access = ({ req }) => {
  if (isStaff(req.user as never)) return true
  return {
    or: [{ _status: { equals: 'published' } }, { _status: { exists: false } }],
  }
}

/**
 * ハイライト編成（要求 2-13, 2-14, 2-15）
 *
 * ADR-008: 2-13 と 2-14 は **別レーン・別データソース** として定義する。
 *  - `home_carousel`  … 2-14 ホーム最上部カルーセル。**全ユーザー共通**でパーソナライズしない（補-2-14-1）
 *  - `tournament_daily` … 2-13(a) ホーム中段の大会ハイライト。運営が CMS で手動選定・並べ替え（補-2-13-1）
 *  - `auto_playlist`  … 2-15 ラウンド×選手の自動プレイリスト（補-2-15-1）
 * 2-13(b) の「お気に入り選手のプレー動画」は本コレクションではなく、
 * ユーザーの `favorites` からアプリ側で動的生成する（補-2-13-1）。
 */
export const HighlightReels: CollectionConfig = {
  slug: 'highlight-reels',
  labels: { singular: 'ハイライト編成', plural: 'ハイライト編成' },
  admin: {
    group: '動画',
    useAsTitle: 'title',
    defaultColumns: ['title', 'type', 'tournament', 'round', 'publishedAt', '_status'],
    description:
      'ADR-008: home_carousel（2-14 ホーム最上部・全ユーザー共通・運営編成）と tournament_daily（2-13 ホーム中段・大会ハイライト）は別レーン・別データソースです',
  },
  // 補-8-8-3: 下書き / 公開のバージョニング
  versions: {
    drafts: true,
    maxPerDoc: 20,
  },
  access: {
    read: readPublished,
    create: editorOnly,
    update: editorOnly,
    delete: editorOnly,
  },
  fields: [
    { name: 'title', type: 'text', label: 'タイトル', required: true },
    {
      name: 'type',
      type: 'select',
      label: '編成種別',
      required: true,
      index: true,
      defaultValue: 'home_carousel',
      options: [
        { label: 'ホームカルーセル（2-14 全ユーザー共通）', value: 'home_carousel' },
        { label: '大会デイリーハイライト（2-13）', value: 'tournament_daily' },
        { label: '自動プレイリスト（2-15）', value: 'auto_playlist' },
      ],
      admin: {
        description:
          'ADR-008 / 補-2-14-2 の要。' +
          'home_carousel = 2-14: ホーム画面**最上部**のカルーセル。**全ユーザー共通**でパーソナライズしない。5 秒自動送り・最大 8 件（補-2-14-1）。' +
          'tournament_daily = 2-13(a): ホーム**中段**の大会ハイライト。運営が CMS で手動選定・並べ替え（補-2-13-1）。' +
          'なお 2-13(b) のお気に入り選手プレー動画はユーザー依存の動的生成のため本コレクションには保存しません。' +
          'auto_playlist = 2-15: ラウンド×選手の自動生成プレイリスト（補-2-15-1）。',
      },
    },
    {
      name: 'tournament',
      type: 'relationship',
      relationTo: 'tournaments',
      label: '大会',
      index: true,
      admin: { description: 'tournament_daily（2-13）では必須運用' },
    },
    {
      name: 'round',
      type: 'relationship',
      relationTo: 'rounds',
      label: 'ラウンド',
      index: true,
      admin: { description: '2-13 のデイリー編成 / 2-15 の対象ラウンド' },
    },
    {
      name: 'player',
      type: 'relationship',
      relationTo: 'players',
      label: '選手',
      index: true,
      admin: { description: '2-15 の対象選手（ラウンド×選手）' },
    },
    {
      name: 'items',
      type: 'relationship',
      relationTo: 'videos',
      hasMany: true,
      label: '収録動画',
      admin: {
        description:
          '2-13。運営が手動で並べ替え可能（ドラッグで順序変更）。auto_playlist は生成結果を保持せず参照のみ（補-2-15-1）',
      },
    },
    {
      name: 'isAutoGenerated',
      type: 'checkbox',
      label: '自動生成',
      defaultValue: false,
      admin: { description: '2-15。自動生成された編成であることを示します' },
    },
    {
      name: 'publishedAt',
      type: 'date',
      label: '公開日時',
      index: true,
      admin: { position: 'sidebar' },
    },
    {
      name: 'order',
      type: 'number',
      label: '表示順',
      defaultValue: 0,
      admin: { position: 'sidebar', description: '昇順で表示。カルーセルは最大 8 件（補-2-14-1）' },
    },
  ],
}

export default HighlightReels
