/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'ad-creatives': AdCreative;
    'ad-slots': AdSlot;
    'analytics-events': AnalyticsEvent;
    courses: Course;
    'device-tokens': DeviceToken;
    faqs: Faq;
    favorites: Favorite;
    'glossary-terms': GlossaryTerm;
    'guest-sessions': GuestSession;
    'guide-articles': GuideArticle;
    'highlight-reels': HighlightReel;
    'hole-statistics': HoleStatistic;
    holes: Hole;
    inquiries: Inquiry;
    likes: Like;
    'live-streams': LiveStream;
    media: Media;
    news: News;
    'notification-settings': NotificationSetting;
    notifications: Notification;
    'onboarding-slides': OnboardingSlide;
    pairings: Pairing;
    'player-positions': PlayerPosition;
    'player-stories': PlayerStory;
    players: Player;
    playlists: Playlist;
    rankings: Ranking;
    rounds: Round;
    scores: Score;
    seasons: Season;
    shots: Shot;
    sponsors: Sponsor;
    'ticket-orders': TicketOrder;
    'ticket-types': TicketType;
    tournaments: Tournament;
    'transport-infos': TransportInfo;
    users: User;
    'venue-facilities': VenueFacility;
    venues: Venue;
    videos: Video;
    'weather-forecasts': WeatherForecast;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'ad-creatives': AdCreativesSelect<false> | AdCreativesSelect<true>;
    'ad-slots': AdSlotsSelect<false> | AdSlotsSelect<true>;
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'device-tokens': DeviceTokensSelect<false> | DeviceTokensSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    'glossary-terms': GlossaryTermsSelect<false> | GlossaryTermsSelect<true>;
    'guest-sessions': GuestSessionsSelect<false> | GuestSessionsSelect<true>;
    'guide-articles': GuideArticlesSelect<false> | GuideArticlesSelect<true>;
    'highlight-reels': HighlightReelsSelect<false> | HighlightReelsSelect<true>;
    'hole-statistics': HoleStatisticsSelect<false> | HoleStatisticsSelect<true>;
    holes: HolesSelect<false> | HolesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    likes: LikesSelect<false> | LikesSelect<true>;
    'live-streams': LiveStreamsSelect<false> | LiveStreamsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'notification-settings': NotificationSettingsSelect<false> | NotificationSettingsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'onboarding-slides': OnboardingSlidesSelect<false> | OnboardingSlidesSelect<true>;
    pairings: PairingsSelect<false> | PairingsSelect<true>;
    'player-positions': PlayerPositionsSelect<false> | PlayerPositionsSelect<true>;
    'player-stories': PlayerStoriesSelect<false> | PlayerStoriesSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    playlists: PlaylistsSelect<false> | PlaylistsSelect<true>;
    rankings: RankingsSelect<false> | RankingsSelect<true>;
    rounds: RoundsSelect<false> | RoundsSelect<true>;
    scores: ScoresSelect<false> | ScoresSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    shots: ShotsSelect<false> | ShotsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'ticket-orders': TicketOrdersSelect<false> | TicketOrdersSelect<true>;
    'ticket-types': TicketTypesSelect<false> | TicketTypesSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    'transport-infos': TransportInfosSelect<false> | TransportInfosSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'venue-facilities': VenueFacilitiesSelect<false> | VenueFacilitiesSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'weather-forecasts': WeatherForecastsSelect<false> | WeatherForecastsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'legal-documents': LegalDocument;
    'app-settings': AppSetting;
  };
  globalsSelect: {
    'legal-documents': LegalDocumentsSelect<false> | LegalDocumentsSelect<true>;
    'app-settings': AppSettingsSelect<false> | AppSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 8-3 / 8-5。補-8-3-2 により大会別・選手別に出し分け、未設定のものを全体配信としてフォールバックする。補-8-9-2 により sponsor ロールには自社分のみ表示
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-creatives".
 */
export interface AdCreative {
  id: number;
  /**
   * 8-3。CMS 上の識別名
   */
  name: string;
  /**
   * 補-8-9-2。sponsor ロールはこの値が自社と一致するものだけ参照できる
   */
  sponsor: number | Sponsor;
  /**
   * 補-8-3-1。配信先の枠
   */
  slot: number | AdSlot;
  /**
   * 補-8-3-2。大会別配信。未設定の場合は全体配信としてフォールバックに使う
   */
  tournament?: (number | null) | Tournament;
  /**
   * 補-8-3-2。選手別配信。未設定の場合は全体配信としてフォールバックに使う
   */
  player?: (number | null) | Player;
  /**
   * 補-8-3-3。format=banner のとき使用
   */
  image?: (number | null) | Media;
  /**
   * 補-8-3-3。format=video のとき使用（video_pre 枠など）
   */
  video?: (number | null) | Video;
  /**
   * 補-8-3-3。format=tieup_article のとき使用
   */
  article?: (number | null) | News;
  /**
   * 8-5。タップ時の遷移先。未設定時はスポンサーの landingUrl を使う
   */
  linkUrl?: string | null;
  /**
   * 補-8-3-4。同一枠に複数候補がある場合の重み付きランダム選択に使う
   */
  weight: number;
  /**
   * 補-8-3-4。配信期間での絞り込みに使う
   */
  startAt?: string | null;
  /**
   * 補-8-3-4。配信期間での絞り込みに使う
   */
  endAt?: string | null;
  /**
   * 補-8-3-4。OFF のクリエイティブは配信対象から除外する
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 8-3 / 8-5。補-8-9-2 により sponsor ロールのユーザーは自社データのみ参照できる
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  /**
   * 8-3
   */
  name: string;
  /**
   * 8-4。表示回数レポートの対象となるスポンサーロゴ
   */
  logo?: (number | null) | Media;
  /**
   * 8-3。スポンサー価値に応じた区分（元表に値の定義がないため 4 段階で仮置き）
   */
  tier?: ('platinum' | 'gold' | 'silver' | 'bronze') | null;
  /**
   * 8-3
   */
  contractFrom?: string | null;
  /**
   * 8-3
   */
  contractTo?: string | null;
  /**
   * 8-5。ロゴ・バナータップ時の遷移先（クリエイティブ側の linkUrl が優先）
   */
  landingUrl?: string | null;
  /**
   * 補-8-4-1。表示回数/クリック/CTR/視聴時間合計/平均視聴完了率を過去30日分で自動集計（保存されない）。sponsor ロールは自社分のみ表示（他社は非表示）。期間を指定したい場合は GET /api/reports/sponsor を使用
   */
  adReportSummary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * 補-8-3-1。Ph1 の 5 枠: home_top_banner / home_inline / leaderboard_inline（10 行ごと）/ video_pre（動画再生前）/ tournament_detail_banner。補-8-5-1 によりクリエイティブ未設定時は枠を非表示にする
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-slots".
 */
export interface AdSlot {
  id: number;
  /**
   * 補-8-3-1。Ph1 の 5 枠: home_top_banner / home_inline / leaderboard_inline / video_pre / tournament_detail_banner。アプリ側はこのキーで枠を引き当てる
   */
  key: string;
  /**
   * 8-3。CMS 上の表示名
   */
  name: string;
  /**
   * 補-8-3-3。バナー画像 / 動画CM / タイアップ記事（news 参照）の 3 種
   */
  format: 'banner' | 'video' | 'tieup_article';
  /**
   * 8-5。表示サイズの目安（例: 320x100, 16:9）
   */
  size?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  name: string;
  /**
   * URL 用の一意な識別子
   */
  slug: string;
  /**
   * 補-1-3-3。シーズン切替セレクタで絞り込みます
   */
  season: number | Season;
  venue: number | Venue;
  course: number | Course;
  startDate: string;
  endDate: string;
  /**
   * 補-1-3-2。大会一覧の行に表示します
   */
  prizeMoneyTotal: number;
  /**
   * 補-1-3-2 のステータスバッジ。補-1-23-4 により cancelled / postponed の間はアプリ上部に赤バナーを表示します
   */
  status: 'scheduled' | 'live' | 'finished' | 'cancelled' | 'postponed';
  /**
   * 補-1-8-1 の大会詳細ヘッダー
   */
  heroImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 1-13 / 補-1-13-1。PDF と Web URL の両方がある場合は PDF を優先
   */
  pamphletPdf?: (number | null) | Media;
  /**
   * 1-13 / 補-1-13-1
   */
  pamphletWebUrl?: string | null;
  /**
   * 1-26 / 補-1-26-1。購入は外部 EC へ遷移します
   */
  officialStoreUrl?: string | null;
  /**
   * 5-1
   */
  ticketUrl?: string | null;
  /**
   * 1-8。何ラウンド終了時点で予選カットを行うか（既定 2）
   */
  cutLineAfterRound?: number | null;
  /**
   * 1-8
   */
  cutRule?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  /**
   * 補-1-3-3。シーズン切替セレクタの既定は現行シーズン
   */
  year: number;
  name: string;
  startDate: string;
  endDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: number;
  name: string;
  /**
   * URL 用の一意な識別子
   */
  slug: string;
  address?: string | null;
  /**
   * 1-17。会場マップ（1-22）の中心座標としても使用します
   */
  location: {
    lat: number;
    lng: number;
  };
  /**
   * 補-1-17-1。アクセスは 電車 / 車 / シャトルバス の 3 セクション
   */
  accessTrain?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 補-1-17-1
   */
  accessCar?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 補-1-17-1。大会ごとのシャトル運行は transport-infos（type=shuttle）を使用し、ここは会場常設の運行を記載します
   */
  shuttleTimetable?:
    | {
        time: string;
        from?: string | null;
        to?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 1-22
   */
  venueMapImage?: (number | null) | Media;
  /**
   * 1-14 / 補-1-14-1。外部マップ起動と QR 表示に使用します
   */
  googleMapUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  name: string;
  venue: number | Venue;
  /**
   * 補-1-19-1。18 ホール合計のパー
   */
  par: number;
  totalYards?: number | null;
  /**
   * 1-19
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 1-20
   */
  layoutImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * 選手マスタ（4-1 / 4-6 / 4-7 / 8-14）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  /**
   * 4-7 プロフィール（和名）
   */
  name: string;
  /**
   * 補-4-7-2 氏名（和/英）
   */
  nameEn?: string | null;
  /**
   * 4-1 選手詳細の URL 識別子
   */
  slug: string;
  /**
   * 8-14 / 補-8-14-1, 補-8-14-3: 推奨レギュレーション = 正方形（1:1）・800×800px 以上・背景統一・顔が中央 40% に収まるよう撮影。800px 未満または非正方形の場合は保存後に下の「写真レギュレーション警告」に表示されます（保存はブロックされません）。未登録時はアプリ側でイニシャル表示のプレースホルダを出します（写真なしの空欄を作らない）
   */
  photo?: (number | null) | Media;
  /**
   * 補-8-14-3。保存時に自動チェックされます（800px 未満 / 非正方形の場合に表示）。背景統一・顔の中央配置は自動判定できないため目視で確認してください
   */
  photoRegulationWarning?: string | null;
  /**
   * 補-4-7-2（年齢は生年月日から算出）
   */
  birthDate?: string | null;
  /**
   * 補-4-7-2
   */
  height?: number | null;
  /**
   * 補-4-7-2
   */
  weight?: number | null;
  /**
   * 補-4-7-2
   */
  birthPlace?: string | null;
  /**
   * 補-4-7-2
   */
  turnedProYear?: number | null;
  /**
   * 4-7 選手詳細のプロフィールタブ
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 補-4-7-2 経歴ハイライト
   */
  careerHighlights?:
    | {
        year: number;
        title: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 4-6 / 補-4-6-1: カテゴリごとにブランド・モデル・写真。補-4-6-2 で users.golfClubSetting と突き合わせて「自分と同じ」バッジを出す
   */
  equipment?:
    | {
        category: 'driver' | 'iron' | 'wedge' | 'putter' | 'ball' | 'wear' | 'shoes';
        brand: string;
        model?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 8-3 選手に紐づくスポンサー
   */
  sponsors?: (number | Sponsor)[] | null;
  /**
   * 4-1 選手一覧の表示対象
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ショット動画・ハイライト・縦型ストーリーを管理します（2-8〜2-15）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * 共有 URL `/watch/<slug>` に使用します（補-2-21-2）
   */
  slug: string;
  /**
   * shot=2-8 全ショット動画 / highlight=2-13, 2-14 ハイライト / story_vertical=2-12 縦型ショート / player_story=4-1 選手ストーリー / live_archive=補-2-1-2 配信アーカイブ
   */
  kind: 'shot' | 'highlight' | 'story_vertical' | 'player_story' | 'live_archive';
  /**
   * 補-8-8-2: アップロード再生用（MOCK）。HLS 配信時は hlsUrl を使用します。公開（公開ステータス）にするには file / hlsUrl のいずれかが必須です
   */
  file?: (number | null) | Media;
  /**
   * 実配信基盤に接続する際はこの値のみ差し替えます（補-2-2-3）
   */
  hlsUrl?: string | null;
  /**
   * OGP 画像未設定時のフォールバックにも使用します（補-2-22-1）
   */
  thumbnail: number | Media;
  /**
   * 縦型ストーリーは 15〜60 秒を想定（補-2-12-2）
   */
  durationSec?: number | null;
  /**
   * 2-12 縦型ストーリーは portrait を指定します
   */
  orientation?: ('landscape' | 'portrait') | null;
  /**
   * 2-8 検索フィルタ軸（補-2-8-1）
   */
  tournament?: (number | null) | Tournament;
  /**
   * 2-8 検索フィルタ軸（補-2-8-1）
   */
  round?: (number | null) | Round;
  /**
   * 2-8 検索フィルタ軸（補-2-8-1）
   */
  player?: (number | null) | Player;
  /**
   * 2-9 / 補-2-15-1 の並べ替えキー（hole 昇順）
   */
  hole?: number | null;
  /**
   * 2-9 / 補-2-15-1 の並べ替えキー（shotNo 昇順）
   */
  shotNo?: number | null;
  /**
   * 2-9
   */
  shotTime?: string | null;
  /**
   * 2-9 / 2-8 検索フィルタ軸（補-2-8-1）。shots.shotType と同一の選択肢
   */
  shotType?: ('tee' | 'approach' | 'bunker' | 'recovery' | 'putt' | 'penalty') | null;
  /**
   * 2-9。ミニマップ上で打点→停止点の線として表示します（補-2-9-2）
   */
  startLocation?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * 2-9。ミニマップ上で打点→停止点の線として表示します（補-2-9-2）
   */
  endLocation?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * 補-2-10-1 の 8 種。2-8 検索フィルタ軸（補-2-8-1）。自動付与ロジックは src/lib/autoTag.ts（補-2-10-2）
   */
  tags?:
    ('eagle' | 'birdie' | 'hole_in_one' | 'long_putt' | 'nice_shot' | 'approach' | 'bunker_save' | 'drive')[] | null;
  /**
   * 補-2-10-3。自動付与されたタグであることを示します。人手修正後は自動再付与しません（チェックを外して保存）
   */
  autoTagged?: boolean | null;
  /**
   * 一覧は publishedAt 降順（補-2-8-2 新着順）
   */
  publishedAt: string;
  /**
   * 2-22。未設定時の既定フォーマット: `{選手名} {大会名} {ラウンド}R {ホール}H - {タグ}`（補-2-22-2）
   */
  ogTitle?: string | null;
  /**
   * 2-22。未設定時は thumbnail を使用（補-2-22-1）
   */
  ogImage?: (number | null) | Media;
  /**
   * 2-21。既定は `https://<cms>/watch/<slug>`（補-2-21-2）。動画ファイルの DL は提供しません（ADR-009）
   */
  shareUrl?: string | null;
  /**
   * 8-4 の視聴集計から更新
   */
  viewCount?: number | null;
  /**
   * 2-11。補-2-8-2 の「人気順」ソートに使用
   */
  likeCount?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rounds".
 */
export interface Round {
  id: number;
  tournament: number | Tournament;
  /**
   * 1〜4（1R〜最終日）
   */
  number: number;
  date: string;
  /**
   * 補-1-23-1。中断（suspended）は緊急通知の種別と連動します
   */
  status: 'scheduled' | 'live' | 'finished' | 'suspended';
  updatedAt: string;
  createdAt: string;
}
/**
 * 1-9〜1-12。編集可能ロールは admin / editor（補-1-12-2）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * ニュース詳細 URL に使用します
   */
  slug: string;
  /**
   * 1-10。見出し / 段落 / 画像 / リンク / 引用をレンダリングします（補-1-10-1）
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroImage?: (number | null) | Media;
  /**
   * 1-9 大会詳細のニュースタブ / 補-1-10-2 の「関連大会」チップ
   */
  tournament?: (number | null) | Tournament;
  /**
   * 4-2 のお気に入り選手ニュース判定に使用します。1-9 の出場選手ニュース / 補-1-10-2 の「関連選手」チップにも使用
   */
  players?: (number | Player)[] | null;
  category?: ('tournament' | 'player' | 'announcement') | null;
  /**
   * 補-1-12-1。未来日時を指定すると予約公開扱い（一覧 API は publishedAt <= now で絞り込み）
   */
  publishedAt: string;
  /**
   * 1-11。ホームの最新ニュースで最上位に表示します（以降 publishedAt 降順で計 5 件／補-1-11-1）
   */
  isPinned?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 8-4 / 8-6 / 8-7。補-8-6-2 によりクライアントからバッチ送信される。集計は /api/reports/sponsor（補-8-4-1）、GA4 転送は MOCK（補-8-7-1）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: number;
  /**
   * 8-6 / 8-7。補-8-6-1 によりインプレッションは 50%・1 秒以上で 1 回。補-8-7-2 により screen_view は画面遷移フックで自動送信。補-8-4-2 により video_progress は 25/50/75/100% 到達で送信
   */
  eventName: 'screen_view' | 'impression' | 'click' | 'video_start' | 'video_progress' | 'video_complete' | 'share';
  /**
   * 8-4。補-8-4-1 のレポート（from/to）で期間絞り込みに使う。クライアント発生時刻
   */
  occurredAt: string;
  /**
   * 8-7。ログイン済みの場合に設定
   */
  userId?: (number | null) | User;
  /**
   * 補-6-1-1 / 8-7。ゲスト（未ログイン）の場合に設定
   */
  deviceId?: string | null;
  /**
   * 補-8-7-2。screen_view の対象画面（expo-router のルート名）
   */
  screen?: string | null;
  /**
   * 8-6。impression / click の対象クリエイティブ。補-8-9-2 により sponsor ロールはこの値が自社のものだけ参照できる
   */
  adCreative?: (number | null) | AdCreative;
  /**
   * 8-4。video_start / video_progress / video_complete の対象動画
   */
  video?: (number | null) | Video;
  /**
   * 8-4。補-8-4-2 により video_progress の到達地点から視聴時間を集計する
   */
  durationSec?: number | null;
  /**
   * 8-7。補-8-7-1 の GA4 Measurement Protocol 変換に渡す任意パラメータ（例: progressPercent, shareTarget）
   */
  props?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 補-8-9-3。ロール変更は admin のみ可能。自分自身のロールは変更できません
   */
  role: 'admin' | 'editor' | 'operator' | 'sponsor' | 'fan';
  /**
   * sponsor ロールの場合、このスポンサーのデータのみ閲覧できます（補-8-9-2）
   */
  sponsor?: (number | null) | Sponsor;
  displayName: string;
  fullName?: string | null;
  birthYear?: number | null;
  gender?: ('male' | 'female' | 'other' | 'undisclosed') | null;
  postalCode?: string | null;
  prefecture?: string | null;
  address?: string | null;
  phone?: string | null;
  golfExperienceYears?: number | null;
  favoritePlayerText?: string | null;
  avatar?: (number | null) | Media;
  snsAccounts?:
    | {
        provider: 'google' | 'apple' | 'line' | 'x' | 'instagram';
        accountId: string;
        /**
         * 補-6-4-1。/api/auth/social/:provider (mode=link) で設定
         */
        linkedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  golfClubSetting?:
    | {
        category: 'driver' | 'iron' | 'wedge' | 'putter' | 'ball' | 'wear' | 'shoes';
        brand: string;
        model?: string | null;
        id?: string | null;
      }[]
    | null;
  twoFactorEnabled?: boolean | null;
  twoFactorSecret?: string | null;
  /**
   * 発行時に平文で 1 回だけ表示し、保存時は SHA-256 ハッシュのみを保持する
   */
  twoFactorRecoveryCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  onboardingCompleted?: boolean | null;
  /**
   * 6-16。OFF でも緊急通知（1-23）は配信されます
   */
  notificationMaster?: boolean | null;
  /**
   * 補-6-15-2
   */
  agreedTermsVersion?: string | null;
  /**
   * 6-7 論理削除。値がある場合はログイン不可
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * プッシュ通知の送信先トークン。未ログインでも deviceId で保持する（補-6-1-1）。退会時は物理削除する（補-6-7-2）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-tokens".
 */
export interface DeviceToken {
  id: number;
  /**
   * Expo / FCM / APNs のデバイストークン
   */
  token: string;
  platform: 'ios' | 'android';
  /**
   * ログインユーザーの場合に設定
   */
  owner?: (number | null) | User;
  /**
   * ゲスト（未ログイン）の場合に設定
   */
  deviceId?: string | null;
  /**
   * 長期間未使用のトークンは配信対象から除外する
   */
  lastActiveAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 6-13。よくある質問。補-6-13-1 のカテゴリ別アコーディオンで表示する
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * 6-13
   */
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 補-6-13-1
   */
  category?: ('account' | 'ticket' | 'video' | 'notification' | 'onsite' | 'other') | null;
  /**
   * 昇順で表示。同一カテゴリ内の並び順
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 4-12 / 4-13。1 ユーザー（または 1 端末）あたりの上限は 10 名（ADR-006 / 補-4-12-1）。アプリ側に加え、beforeChange フックでサーバー側でも作成時に強制する
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  /**
   * ログインユーザーの場合に設定
   */
  owner?: (number | null) | User;
  /**
   * ゲスト（未ログイン）の場合に設定
   */
  deviceId?: string | null;
  /**
   * 4-12。お気に入り登録した選手
   */
  player: number | Player;
  /**
   * 補-4-12-3。お気に入り一覧のドラッグ＆ドロップ並べ替え結果。この順序はリーダーボードの絞り込み表示・通知一覧の並びにも反映する
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 1-2。バーディ／ボギー／プレーオフ等のゴルフ用語解説
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms".
 */
export interface GlossaryTerm {
  id: number;
  term: string;
  /**
   * 補-1-2-1。かな検索用。ひらがなで入力します（入力 1 文字からの前方一致検索に使用）
   */
  reading: string;
  /**
   * 補-1-2-1。英字表記や略称も検索対象にします（例: birdie / バーディー）
   */
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 1-2。用語集一覧の絞り込みに使用します
   */
  category?: ('score' | 'rule' | 'shot' | 'course' | 'equipment' | 'tournament' | 'other') | null;
  /**
   * 補-1-2-2。用語詳細に最大 5 件表示します
   */
  relatedTerms?: (number | GlossaryTerm)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 6-1 / 補-6-1-1。未ログイン利用者を deviceId で識別するためのセッション
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guest-sessions".
 */
export interface GuestSession {
  id: number;
  /**
   * 補-6-1-1。端末生成 UUID（アプリ側で SecureStore に保管）
   */
  deviceId: string;
  lastSeenAt?: string | null;
  /**
   * 補-6-1-1。ログイン／新規登録時にゲストデータを移行したユーザー
   */
  linkedUser?: (number | null) | User;
  /**
   * オンボーディング完了状態・表示設定などの端末ローカル設定のスナップショット
   */
  preferences?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 1-1。ゴルフ観戦のルール・マナー初心者ガイド（写真／動画付き）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-articles".
 */
export interface GuideArticle {
  id: number;
  title: string;
  slug: string;
  /**
   * 補-1-1-1 の 3 分類。一覧はカテゴリタブで切り替えます
   */
  category: 'manner' | 'rule' | 'beginner';
  /**
   * 補-1-1-2。用語集へのリンクは手動で設定します（自動リンク化はしない／補-1-2-3）
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 補-1-1-2。0..n 枚
   */
  images?: (number | Media)[] | null;
  /**
   * 補-1-1-2。0..1 本。videos への参照（ガイド専用アップロードはしません）
   */
  video?: (number | null) | Video;
  /**
   * カテゴリ内の表示順（昇順）
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * ADR-008: home_carousel（2-14 ホーム最上部・全ユーザー共通・運営編成）と tournament_daily（2-13 ホーム中段・大会ハイライト）は別レーン・別データソースです
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight-reels".
 */
export interface HighlightReel {
  id: number;
  title: string;
  /**
   * ADR-008 / 補-2-14-2 の要。home_carousel = 2-14: ホーム画面**最上部**のカルーセル。**全ユーザー共通**でパーソナライズしない。5 秒自動送り・最大 8 件（補-2-14-1）。tournament_daily = 2-13(a): ホーム**中段**の大会ハイライト。運営が CMS で手動選定・並べ替え（補-2-13-1）。なお 2-13(b) のお気に入り選手プレー動画はユーザー依存の動的生成のため本コレクションには保存しません。auto_playlist = 2-15: ラウンド×選手の自動生成プレイリスト（補-2-15-1）。
   */
  type: 'home_carousel' | 'tournament_daily' | 'auto_playlist';
  /**
   * tournament_daily（2-13）では必須運用
   */
  tournament?: (number | null) | Tournament;
  /**
   * 2-13 のデイリー編成 / 2-15 の対象ラウンド
   */
  round?: (number | null) | Round;
  /**
   * 2-15 の対象選手（ラウンド×選手）
   */
  player?: (number | null) | Player;
  /**
   * 2-13。運営が手動で並べ替え可能（ドラッグで順序変更）。auto_playlist は生成結果を保持せず参照のみ（補-2-15-1）
   */
  items?: (number | Video)[] | null;
  /**
   * 2-15。自動生成された編成であることを示します
   */
  isAutoGenerated?: boolean | null;
  publishedAt?: string | null;
  /**
   * 昇順で表示。カルーセルは最大 8 件（補-2-14-1）
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * エリア別ショット成功確率の事前集計（1-47 / 補-1-47-1）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hole-statistics".
 */
export interface HoleStatistic {
  id: number;
  /**
   * 1-47 集計対象の大会
   */
  tournament: number | Tournament;
  /**
   * 1-47 集計対象ホール
   */
  hole: number;
  /**
   * 補-1-47-1 コースマップ上のゾーン区分（Birdie% でヒートマップ表示）
   */
  zone: 'fw_left' | 'fw_center' | 'fw_right' | 'rough_left' | 'rough_right' | 'bunker' | 'green';
  /**
   * 補-1-47-1 ヒートマップの色分け基準
   */
  birdieRate?: number | null;
  /**
   * 補-1-47-2 ゾーンタップ時に表示
   */
  parRate?: number | null;
  /**
   * 補-1-47-2 ゾーンタップ時に表示
   */
  bogeyRate?: number | null;
  /**
   * 補-1-47-2 ゾーンタップ時に表示
   */
  avgStrokes?: number | null;
  /**
   * 補-1-47-2: 30 未満のゾーンはアプリ側で「参考値」と注記する
   */
  sampleSize?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holes".
 */
export interface Hole {
  id: number;
  course: number | Course;
  /**
   * 補-1-19-1。1〜18
   */
  number: number;
  par: number;
  yards: number;
  /**
   * 補-1-19-1。ホール難易度順位
   */
  handicap?: number | null;
  /**
   * 補-1-19-2。ホール詳細に表示する攻略ポイント
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 補-1-20-1。写真とイラストはタブで切替
   */
  photo?: (number | null) | Media;
  /**
   * 補-1-20-1
   */
  illustration?: (number | null) | Media;
  /**
   * 1-42。ショットビューの起点
   */
  teeLocation?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * 1-42。ショットビューの着地目標
   */
  greenLocation?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * 補-1-42-1。2D ショットビューで緯度経度 → SVG 座標へ線形変換するための矩形。南西 (sw) と北東 (ne) の 2 点で指定します
   */
  bounds?: {
    swLat?: number | null;
    swLng?: number | null;
    neLat?: number | null;
    neLng?: number | null;
  };
  /**
   * 補-1-42-1。ショットビューに重畳するポリゴン（バンカー / 池 / OB / 樹木）
   */
  hazards?:
    | {
        type: 'bunker' | 'water' | 'ob' | 'tree';
        /**
         * [[緯度, 経度], ...] の配列。閉じた多角形として描画します（補-1-42-1）
         */
        polygon?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 6-14。補-6-14-2 により対応状況のみ CMS で管理し、返信はメール運用で行う
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  /**
   * 補-6-14-1。ログイン時はユーザー情報から自動補完する
   */
  name: string;
  /**
   * 補-6-14-1。返信先（補-6-14-2 によりメール運用）
   */
  email: string;
  /**
   * 補-6-14-1
   */
  category: 'account' | 'ticket' | 'video' | 'notification' | 'onsite' | 'other';
  /**
   * 補-6-14-1
   */
  body: string;
  /**
   * 補-6-14-2
   */
  status: 'open' | 'in_progress' | 'closed';
  /**
   * ログイン済みで送信された場合に設定
   */
  submittedBy?: (number | null) | User;
  /**
   * 補-6-1-1。ゲスト（未ログイン）で送信された場合に設定
   */
  deviceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 2-11（動画のいいね）／1-45（お気に入りショット）。1 レコードにつき video と shot の「どちらか一方」のみを設定する
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "likes".
 */
export interface Like {
  id: number;
  /**
   * ログインユーザーの場合に設定
   */
  owner?: (number | null) | User;
  /**
   * ゲスト（未ログイン）の場合に設定
   */
  deviceId?: string | null;
  /**
   * 2-11 動画のいいね。shot とはどちらか一方のみを設定する
   */
  video?: (number | null) | Video;
  /**
   * 1-45 お気に入りショット。video とはどちらか一方のみを設定する
   */
  shot?: (number | null) | Shot;
  updatedAt: string;
  createdAt: string;
}
/**
 * 1 打ごとのショットデータ（3-3 Play-by-play / 1-42 ショットビュー）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shots".
 */
export interface Shot {
  id: number;
  /**
   * 3-3 対象ラウンド
   */
  round: number | Round;
  /**
   * 3-3 対象選手
   */
  player: number | Player;
  /**
   * 3-3 / 補-1-46-1 ホール切替
   */
  hole: number;
  /**
   * 補-3-3-1 「ホール × ショット順」の時系列フィード
   */
  shotNo: number;
  /**
   * 補-1-42-2 弾道の高さ係数の決定にも使用
   */
  shotType: 'tee' | 'approach' | 'bunker' | 'recovery' | 'putt' | 'penalty';
  /**
   * 3-3 速報表示（使用クラブ）
   */
  club?:
    | (
        | 'driver'
        | '3w'
        | '5w'
        | 'utility'
        | '3i'
        | '4i'
        | '5i'
        | '6i'
        | '7i'
        | '8i'
        | '9i'
        | 'pw'
        | 'aw'
        | 'sw'
        | 'lw'
        | 'putter'
      )
    | null;
  /**
   * 3-3 / 1-42 飛距離ラベル
   */
  distanceYards?: number | null;
  /**
   * 1-42 弾道表示の補助値
   */
  carryYards?: number | null;
  /**
   * 1-42 / 補-1-42-1: 弾道の始点（point は SQLite 非対応のため lat/lng の group）
   */
  startLocation: {
    lat: number;
    lng: number;
  };
  /**
   * 1-46 / 補-1-42-1: ボールの落下・停止地点
   */
  endLocation: {
    lat: number;
    lng: number;
  };
  /**
   * 3-3 速報テキストの生成に使用
   */
  startLie?: ('tee' | 'fairway' | 'rough' | 'bunker' | 'green' | 'hazard' | 'ob') | null;
  /**
   * 補-3-3-1 「着地ライ」の表示
   */
  endLie?: ('tee' | 'fairway' | 'rough' | 'bunker' | 'green' | 'hazard' | 'ob') | null;
  /**
   * 補-3-3-1 「残り距離 → 飛距離 → 着地ライ」の表示
   */
  remainingYards?: number | null;
  /**
   * 3-3 / 補-3-3-2: CMS 入力を優先し、未入力時はアプリ側で属性からテンプレート生成する（例: 1H 2打目 7I 152y → グリーン 残り3.5m）
   */
  resultText?: string | null;
  /**
   * 1-40 / 補-1-40-1: 保存時フックでショット属性からテンプレート生成（実 LLM 呼び出しなし・ADR-003）。CMS で上書き編集可。補-1-40-2 で 40〜80 文字程度・1 文
   */
  aiCommentary?: string | null;
  /**
   * 補-1-40-1: 自動生成された文のままなら true。CMS で上書きすると false になる
   */
  aiCommentaryGenerated?: boolean | null;
  /**
   * 3-3 / 補-3-3-4: 時系列フィードの並び順と 15 秒ポーリングの差分取得に使用
   */
  occurredAt: string;
  /**
   * 1-39 / 補-1-39-1: 値が存在するショットのみ計測データパネルを表示する（MOCK・補-1-39-2 により値のないショットが多い）
   */
  trackman?: {
    ballSpeed?: number | null;
    launchAngle?: number | null;
    spinRate?: number | null;
    apexHeight?: number | null;
  };
  /**
   * 1-38 / 3-8: 補-3-8-2 により動画が無いショットには導線を表示しない（グレーアウトではなく非表示）
   */
  video?: (number | null) | Video;
  updatedAt: string;
  createdAt: string;
}
/**
 * 練習場配信（2-2）・インスタライブ（2-1）の配信枠を管理します
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-streams".
 */
export interface LiveStream {
  id: number;
  title: string;
  tournament: number | Tournament;
  /**
   * practice_range=2-2（固定カメラ 1 系統。UI に選手名を出さない／補-2-2-1）/ instagram_live=2-1 / featured_group=2-1
   */
  kind: 'practice_range' | 'instagram_live' | 'featured_group';
  /**
   * 補-2-1-2。ended になったら archiveVideo へ自動的に切り替えます
   */
  status: 'scheduled' | 'live' | 'ended';
  /**
   * 補-2-2-3。サンプル HLS / ローカル動画を指定します。実配信移行時はこの値のみ差し替えます（MOCK）
   */
  streamUrl?: string | null;
  /**
   * 補-2-1-2。配信終了後に再生する videos（kind=live_archive）
   */
  archiveVideo?: (number | null) | Video;
  startedAt?: string | null;
  endedAt?: string | null;
  /**
   * 2-1 / 補-2-1-1。数分〜2 時間（7200 秒）の遅延を許容。UI に「追っかけ再生」ラベルと遅延時間を表示します
   */
  delaySec?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 4-16 / 4-17 / 6-16。ユーザーまたは端末ごとに 1 レコード。緊急通知（1-23）はマスタースイッチでも停止できない（ADR-015 / 補-6-16-1）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings".
 */
export interface NotificationSetting {
  id: number;
  /**
   * ログインユーザーの場合に設定
   */
  owner?: (number | null) | User;
  /**
   * ゲスト（未ログイン）の場合に設定
   */
  deviceId?: string | null;
  /**
   * 6-16。プッシュ通知全体の ON/OFF。OFF にすると緊急通知を除く全通知を停止する（補-6-16-1）
   */
  master?: boolean | null;
  /**
   * 1-23 / ADR-015。安全に関わる情報のため OFF 不可（常時 true）。マスタースイッチ OFF でも配信される（補-6-16-1）
   */
  emergency?: boolean | null;
  /**
   * 3-5 / 4-19。優勝争い情報のリアルタイム通知。選手別設定とは独立させる（補-4-19-1）
   */
  titleRace?: boolean | null;
  /**
   * 補-4-16-1 の 8 イベント。お気に入り登録していない選手も設定可能（4-16, 4-19 / 補-4-16-2）。初期値はお気に入り選手に対して バーディ / イーグル / スタート30分前 のみ ON（補-4-16-3）
   */
  perPlayer?:
    | {
        player: number | Player;
        /**
         * 補-4-16-1 / 補-4-16-3（初期値 ON）
         */
        birdie?: boolean | null;
        /**
         * 補-4-16-1 / 補-4-16-3（初期値 ON）
         */
        eagle?: boolean | null;
        /**
         * 補-4-16-1
         */
        bogeyOrWorse?: boolean | null;
        /**
         * 補-4-16-1。確定通知は 4-18 側（補-4-18-1）
         */
        cutLineChange?: boolean | null;
        /**
         * 補-4-16-1
         */
        top10?: boolean | null;
        /**
         * 4-17 / 補-4-17-1（初期値 ON）
         */
        startReminder30?: boolean | null;
        /**
         * 4-17 / 補-4-17-1
         */
        startReminder15?: boolean | null;
        /**
         * 4-15 / 補-4-15-1。通算 -4 以下到達、または 1 ホールでイーグル以上（定義は app-settings で変更可）
         */
        goodScore?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 6-17 通知センター。宛先の絞り込みはエンドポイント側で行う。保持期間 30 日・緊急通知は未読の間ピン留め（補-6-17-3）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * emergency は 1-23（マスタースイッチで停止不可 / ADR-015）。player_event=4-16, start_reminder=4-17, title_race=4-19/3-5, news=1-9, cut_line=4-18
   */
  type: 'emergency' | 'player_event' | 'start_reminder' | 'title_race' | 'news' | 'cut_line';
  title: string;
  body: string;
  /**
   * 補-6-17-2。タップで該当画面（リーダーボード／選手詳細／大会詳細／動画）へ遷移する URL
   */
  deepLink?: string | null;
  tournament?: (number | null) | Tournament;
  player?: (number | null) | Player;
  /**
   * 6-17。絞り込みはエンドポイント側で実施
   */
  audience: 'all' | 'user' | 'device';
  /**
   * audience=user のときの宛先
   */
  targetUser?: (number | null) | User;
  /**
   * 補-6-1-1。audience=device のときの宛先（ゲスト向け）
   */
  targetDeviceId?: string | null;
  sentAt: string;
  /**
   * 補-6-17-1。既読/未読の管理に使用（未読数をタブバーのバッジに表示）
   */
  readBy?: (number | User)[] | null;
  /**
   * 補-6-17-3。緊急通知は high とし、未読の間は一覧最上位にピン留めする
   */
  priority?: ('high' | 'normal' | 'low') | null;
  /**
   * T-14-2。run-checks（判定ジョブ）が同一イベント×宛先の重複生成を防ぐための内部キー。手動発行（緊急通知等）では未設定のままでよい
   */
  dedupeKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 6-12。補-6-12-1 の 4 スライド（アプリでできること / リーダーボード / 動画 / お気に入り）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-slides".
 */
export interface OnboardingSlide {
  id: number;
  /**
   * 6-12
   */
  title: string;
  body?: string | null;
  image?: (number | null) | Media;
  /**
   * 補-6-12-1。昇順で表示。最終スライドに「お気に入り選手を選ぶ」「あとで」を置く
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pairings".
 */
export interface Pairing {
  id: number;
  /**
   * 補-1-8-2。組み合わせはラウンド別に管理します
   */
  round: number | Round;
  /**
   * 補-1-8-2
   */
  groupNo: number;
  /**
   * 補-1-8-2
   */
  startTime: string;
  /**
   * 補-1-8-2。1（アウト）または 10（イン）のみ
   */
  startHole: number;
  /**
   * 補-1-8-2。1 組 2〜3 名。補-1-8-3 のお気に入りフィルタ対象
   */
  players?: (number | Player)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 1-31。補-1-31-1 のとおり更新間隔は 30 秒で、参照は選手ごとの最新 1 件のみ（recordedAt 降順）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-positions".
 */
export interface PlayerPosition {
  id: number;
  tournament: number | Tournament;
  player: number | Player;
  /**
   * 1-31。選手の現在地（緯度・経度）
   */
  location: {
    lat: number;
    lng: number;
  };
  /**
   * 1-31。プレー中のホール
   */
  hole?: number | null;
  /**
   * 補-1-31-1。30 秒間隔で記録。最新 1 件のみを参照するため索引必須
   */
  recordedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * 選手ストーリー記事（4-1 / 補-4-1-1）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-stories".
 */
export interface PlayerStory {
  id: number;
  /**
   * 4-1 対象選手
   */
  player: number | Player;
  /**
   * 4-1
   */
  title: string;
  /**
   * 補-4-1-1 テキストパート
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 補-4-1-1 動画パート（2-13 ストーリー動画レーンと共通）
   */
  video?: (number | null) | Video;
  /**
   * 4-1 新着順の基準
   */
  publishedAt: string;
  /**
   * 4-1 選手詳細ストーリータブ内の並び順
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 2-23。いいね動画から作成するユーザー個別の再生リスト
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists".
 */
export interface Playlist {
  id: number;
  name: string;
  /**
   * ログインユーザーの場合に設定
   */
  owner?: (number | null) | User;
  /**
   * ゲスト（未ログイン）の場合に設定
   */
  deviceId?: string | null;
  /**
   * 補-2-23-1。1 プレイリスト最大 50 本（1 ユーザー最大 20 件）。いいね動画から追加します（補-2-11-1）
   */
  items?: (number | Video)[] | null;
  /**
   * 補-2-23-2。ON の場合、shareToken 付き URL で未ログインでも閲覧できます（編集は所有者のみ）
   */
  isPublic?: boolean | null;
  /**
   * 補-2-23-2。共有 URL に付与するトークン。トークン経由の閲覧は専用エンドポイントで提供します
   */
  shareToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 賞金・ポイント・各種スタッツランキング（1-5 / 1-6 / 1-7）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings".
 */
export interface Ranking {
  id: number;
  /**
   * 1-5 対象シーズン
   */
  season: number | Season;
  /**
   * 1-5 / 1-6 / 1-7。type ごとに最新 1 レコードを参照する
   */
  type:
    | 'money'
    | 'points'
    | 'rookie'
    | 'driving_distance'
    | 'greens_in_regulation'
    | 'sand_save'
    | 'putting'
    | 'scoring_average';
  /**
   * 1-5: この日付が最新のレコードを表示。過去分は前週比表示のため履歴として残す
   */
  asOf: string;
  /**
   * 1-5 / 1-6 / 1-7 の一覧行
   */
  entries?:
    | {
        rank: number;
        player: number | Player;
        /**
         * 賞金額・ポイント・平均値など type に応じた値
         */
        value: number;
        /**
         * 例: 「120,500,000円」「298.4y」。単位付きの整形済み文字列
         */
        valueLabel?: string | null;
        events?: number | null;
        /**
         * 前週比（↑↓）表示に使用
         */
        previousRank?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ラウンド単位のスコア（3-1 リーダーボード / 3-2 Hole-by-Hole / 3-6 スタッツ）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores".
 */
export interface Score {
  id: number;
  /**
   * 3-1 対象ラウンド
   */
  round: number | Round;
  /**
   * 3-1 対象選手
   */
  player: number | Player;
  /**
   * 補-3-1-1 リーダーボードの順位
   */
  position?: number | null;
  /**
   * 補-3-1-4 同スコア時の T 表記に使用
   */
  positionTied?: boolean | null;
  /**
   * 補-3-1-1 Total (To Par)
   */
  toPar: number;
  /**
   * 3-1
   */
  strokes: number;
  /**
   * 補-3-1-1 Thru 列。18 で当該ラウンド終了
   */
  thru?: number | null;
  /**
   * 補-3-1-1 Today 列
   */
  today?: number | null;
  /**
   * 補-3-1-4 CUT / WD / DQ のバッジ表示に使用
   */
  status: 'playing' | 'finished' | 'cut' | 'wd' | 'dq';
  /**
   * 補-4-14-1: 事前計算値。ラウンド終了ごとに CMS 側ジョブで算出する。補-4-14-2 によりアプリ側では 0/25/50/75/100% の 5 段階バッジに丸めて表示する
   */
  cutProbability?: number | null;
  /**
   * 3-2 Hole-by-Hole（18 ホール分）。補-3-2-1 の色分け、補-3-2-2 の OUT/IN 小計はこの配列から算出する
   */
  holeScores?:
    | {
        hole: number;
        par: number;
        strokes: number;
        toPar: number;
        /**
         * 補-3-2-1 の色分け区分
         */
        result: 'eagle' | 'birdie' | 'par' | 'bogey' | 'double_or_worse';
        id?: string | null;
      }[]
    | null;
  /**
   * 3-6 / 補-3-6-1: 選手別スタッツ 6 指標
   */
  stats?: {
    /**
     * 補-3-6-1
     */
    drivingDistance?: number | null;
    /**
     * 補-3-6-1
     */
    fairwayHitRate?: number | null;
    /**
     * 補-3-6-1
     */
    greenInRegulation?: number | null;
    /**
     * 補-3-6-1
     */
    puttsPerRound?: number | null;
    /**
     * 補-3-6-1
     */
    sandSaveRate?: number | null;
    /**
     * 補-3-6-1
     */
    scrambleRate?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * 5-1 / 5-3。決済は MOCK（補-5-1-4）。大会中止時は補-5-1-5 により CMS から一括で status=cancelled にする運用
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-orders".
 */
export interface TicketOrder {
  id: number;
  /**
   * 5-1。補-5-3-2 により券面にも表示する
   */
  orderNo: string;
  /**
   * 補-5-1-2 / 6-1。購入にはログインが必須のためゲスト購入は不可
   */
  user: number | User;
  /**
   * 5-1
   */
  ticketType: number | TicketType;
  /**
   * 5-1。補-5-3-2 により券面にも表示する
   */
  quantity: number;
  /**
   * 5-1。券種価格 × 枚数
   */
  amount: number;
  /**
   * 5-1 / 5-3。補-5-1-4 により MOCK 決済は常に paid。補-5-3-4 により used はデータモデル上のみ（もぎり運用は Ph1 対象外）
   */
  status: 'pending' | 'paid' | 'cancelled' | 'used';
  /**
   * 補-5-1-4。MOCK 決済の参照（例: MOCK-xxxx）。外部決済への差し替え点は 1 関数に隔離する
   */
  paymentRef?: string | null;
  /**
   * 5-3。補-5-3-2 により電子チケットの QR コードに埋め込む文字列。再利用防止の検証は Ph1 対象外
   */
  qrPayload?: string | null;
  /**
   * 5-1。補-5-1-4 の MOCK 決済成功時に設定する
   */
  purchasedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 5-1。補-5-1-3 により、販売期間外・在庫 0 の券種はアプリ側で購入不可として表示されます
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-types".
 */
export interface TicketType {
  id: number;
  /**
   * 5-1。補-5-1-1 により大会詳細の「チケット」ブロックから導線を出す
   */
  tournament: number | Tournament;
  /**
   * 補-5-1-3。例: 1日券 / 通し券 / 駐車券
   */
  name: string;
  /**
   * 5-1。税込価格
   */
  price: number;
  /**
   * 5-3。補-5-3-1 により、status=paid かつ有効日が当日以降のチケットを「有効」として表示する
   */
  validDate?: string | null;
  /**
   * 補-5-1-3。0 の場合は購入不可
   */
  stock?: number | null;
  /**
   * 補-5-1-3
   */
  salesStart?: string | null;
  /**
   * 補-5-1-3
   */
  salesEnd?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transport-infos".
 */
export interface TransportInfo {
  id: number;
  tournament: number | Tournament;
  /**
   * 1-15 / 1-16 / 補-1-17-1。シャトルバスはアクセス画面のシャトル節に表示します
   */
  type: 'gallery_bus' | 'parking' | 'shuttle';
  name: string;
  /**
   * 補-1-15-1 の乗降場所ピン / 補-1-16-1 の駐車場ピン
   */
  location?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * 補-1-15-1。アプリ側で「次の発車」を強調表示します
   */
  timetable?:
    | {
        time: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 補-1-16-1。駐車場の収容台数
   */
  capacity?: number | null;
  /**
   * 補-1-16-2。満車情報は自動計測せず CMS から手動更新します（主に type=parking で使用）
   */
  occupancyStatus?: ('vacant' | 'crowded' | 'full') | null;
  /**
   * 補-1-15-1 の運賃 / 補-1-16-1 の駐車料金
   */
  fee?: string | null;
  /**
   * 補-1-16-1
   */
  note?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-facilities".
 */
export interface VenueFacility {
  id: number;
  venue: number | Venue;
  /**
   * 任意。大会開催期間のみ設置される施設に指定します
   */
  tournament?: (number | null) | Tournament;
  /**
   * 補-1-22-1。会場マップのピン種別は トイレ / 飲食 / グッズ / 救護所 / 入場ゲート / 案内所 / 喫煙所 / ATM の 8 種
   */
  type: 'toilet' | 'food' | 'goods' | 'firstaid' | 'entrance' | 'info' | 'smoking' | 'atm';
  name: string;
  /**
   * 補-1-22-1。実地図上に重畳する施設ピンの座標
   */
  location: {
    lat: number;
    lng: number;
  };
  /**
   * 補-1-22-2。ピンタップ時のボトムシートに表示します
   */
  description?: string | null;
  photo?: (number | null) | Media;
  /**
   * 補-1-25-1。グルメ・お土産は type=food / goods のメニュー配列で表現します（写真・価格・場所を表示）
   */
  menuItems?:
    | {
        name: string;
        price?: number | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 補-1-22-2
   */
  openHours?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weather-forecasts".
 */
export interface WeatherForecast {
  id: number;
  tournament: number | Tournament;
  /**
   * 補-1-24-3。この予報を取得（投入）した日時
   */
  observedAt: string;
  /**
   * 補-1-24-1。1 時間刻み × 72 時間（今日 / 明日 / 明後日タブ）
   */
  forecastFor: string;
  /**
   * 補-1-24-2。アプリ側で天候アイコンに変換して表示します
   */
  condition: 'sunny' | 'partly_cloudy' | 'cloudy' | 'rain' | 'heavy_rain' | 'thunder' | 'snow' | 'fog';
  /**
   * 補-1-24-2
   */
  temperature?: number | null;
  /**
   * 補-1-24-2
   */
  windSpeed?: number | null;
  /**
   * 補-1-24-2。ゴルフ観戦では風が重要なため矢印アイコンで表現します
   */
  windDirection?: ('N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW') | null;
  /**
   * 補-1-24-2
   */
  precipProbability?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'ad-creatives';
        value: number | AdCreative;
      } | null)
    | ({
        relationTo: 'ad-slots';
        value: number | AdSlot;
      } | null)
    | ({
        relationTo: 'analytics-events';
        value: number | AnalyticsEvent;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'device-tokens';
        value: number | DeviceToken;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'glossary-terms';
        value: number | GlossaryTerm;
      } | null)
    | ({
        relationTo: 'guest-sessions';
        value: number | GuestSession;
      } | null)
    | ({
        relationTo: 'guide-articles';
        value: number | GuideArticle;
      } | null)
    | ({
        relationTo: 'highlight-reels';
        value: number | HighlightReel;
      } | null)
    | ({
        relationTo: 'hole-statistics';
        value: number | HoleStatistic;
      } | null)
    | ({
        relationTo: 'holes';
        value: number | Hole;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'likes';
        value: number | Like;
      } | null)
    | ({
        relationTo: 'live-streams';
        value: number | LiveStream;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'notification-settings';
        value: number | NotificationSetting;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'onboarding-slides';
        value: number | OnboardingSlide;
      } | null)
    | ({
        relationTo: 'pairings';
        value: number | Pairing;
      } | null)
    | ({
        relationTo: 'player-positions';
        value: number | PlayerPosition;
      } | null)
    | ({
        relationTo: 'player-stories';
        value: number | PlayerStory;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'playlists';
        value: number | Playlist;
      } | null)
    | ({
        relationTo: 'rankings';
        value: number | Ranking;
      } | null)
    | ({
        relationTo: 'rounds';
        value: number | Round;
      } | null)
    | ({
        relationTo: 'scores';
        value: number | Score;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'shots';
        value: number | Shot;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'ticket-orders';
        value: number | TicketOrder;
      } | null)
    | ({
        relationTo: 'ticket-types';
        value: number | TicketType;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'transport-infos';
        value: number | TransportInfo;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'venue-facilities';
        value: number | VenueFacility;
      } | null)
    | ({
        relationTo: 'venues';
        value: number | Venue;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'weather-forecasts';
        value: number | WeatherForecast;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-creatives_select".
 */
export interface AdCreativesSelect<T extends boolean = true> {
  name?: T;
  sponsor?: T;
  slot?: T;
  tournament?: T;
  player?: T;
  image?: T;
  video?: T;
  article?: T;
  linkUrl?: T;
  weight?: T;
  startAt?: T;
  endAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-slots_select".
 */
export interface AdSlotsSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  format?: T;
  size?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  eventName?: T;
  occurredAt?: T;
  userId?: T;
  deviceId?: T;
  screen?: T;
  adCreative?: T;
  video?: T;
  durationSec?: T;
  props?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  name?: T;
  venue?: T;
  par?: T;
  totalYards?: T;
  description?: T;
  layoutImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-tokens_select".
 */
export interface DeviceTokensSelect<T extends boolean = true> {
  token?: T;
  platform?: T;
  owner?: T;
  deviceId?: T;
  lastActiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  owner?: T;
  deviceId?: T;
  player?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms_select".
 */
export interface GlossaryTermsSelect<T extends boolean = true> {
  term?: T;
  reading?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  description?: T;
  category?: T;
  relatedTerms?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guest-sessions_select".
 */
export interface GuestSessionsSelect<T extends boolean = true> {
  deviceId?: T;
  lastSeenAt?: T;
  linkedUser?: T;
  preferences?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guide-articles_select".
 */
export interface GuideArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  body?: T;
  images?: T;
  video?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight-reels_select".
 */
export interface HighlightReelsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  tournament?: T;
  round?: T;
  player?: T;
  items?: T;
  isAutoGenerated?: T;
  publishedAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hole-statistics_select".
 */
export interface HoleStatisticsSelect<T extends boolean = true> {
  tournament?: T;
  hole?: T;
  zone?: T;
  birdieRate?: T;
  parRate?: T;
  bogeyRate?: T;
  avgStrokes?: T;
  sampleSize?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holes_select".
 */
export interface HolesSelect<T extends boolean = true> {
  course?: T;
  number?: T;
  par?: T;
  yards?: T;
  handicap?: T;
  description?: T;
  photo?: T;
  illustration?: T;
  teeLocation?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  greenLocation?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  bounds?:
    | T
    | {
        swLat?: T;
        swLng?: T;
        neLat?: T;
        neLng?: T;
      };
  hazards?:
    | T
    | {
        type?: T;
        polygon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  category?: T;
  body?: T;
  status?: T;
  submittedBy?: T;
  deviceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "likes_select".
 */
export interface LikesSelect<T extends boolean = true> {
  owner?: T;
  deviceId?: T;
  video?: T;
  shot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-streams_select".
 */
export interface LiveStreamsSelect<T extends boolean = true> {
  title?: T;
  tournament?: T;
  kind?: T;
  status?: T;
  streamUrl?: T;
  archiveVideo?: T;
  startedAt?: T;
  endedAt?: T;
  delaySec?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  heroImage?: T;
  tournament?: T;
  players?: T;
  category?: T;
  publishedAt?: T;
  isPinned?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings_select".
 */
export interface NotificationSettingsSelect<T extends boolean = true> {
  owner?: T;
  deviceId?: T;
  master?: T;
  emergency?: T;
  titleRace?: T;
  perPlayer?:
    | T
    | {
        player?: T;
        birdie?: T;
        eagle?: T;
        bogeyOrWorse?: T;
        cutLineChange?: T;
        top10?: T;
        startReminder30?: T;
        startReminder15?: T;
        goodScore?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  body?: T;
  deepLink?: T;
  tournament?: T;
  player?: T;
  audience?: T;
  targetUser?: T;
  targetDeviceId?: T;
  sentAt?: T;
  readBy?: T;
  priority?: T;
  dedupeKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-slides_select".
 */
export interface OnboardingSlidesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pairings_select".
 */
export interface PairingsSelect<T extends boolean = true> {
  round?: T;
  groupNo?: T;
  startTime?: T;
  startHole?: T;
  players?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-positions_select".
 */
export interface PlayerPositionsSelect<T extends boolean = true> {
  tournament?: T;
  player?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  hole?: T;
  recordedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-stories_select".
 */
export interface PlayerStoriesSelect<T extends boolean = true> {
  player?: T;
  title?: T;
  body?: T;
  video?: T;
  publishedAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  nameEn?: T;
  slug?: T;
  photo?: T;
  photoRegulationWarning?: T;
  birthDate?: T;
  height?: T;
  weight?: T;
  birthPlace?: T;
  turnedProYear?: T;
  bio?: T;
  careerHighlights?:
    | T
    | {
        year?: T;
        title?: T;
        id?: T;
      };
  equipment?:
    | T
    | {
        category?: T;
        brand?: T;
        model?: T;
        photo?: T;
        id?: T;
      };
  sponsors?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists_select".
 */
export interface PlaylistsSelect<T extends boolean = true> {
  name?: T;
  owner?: T;
  deviceId?: T;
  items?: T;
  isPublic?: T;
  shareToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings_select".
 */
export interface RankingsSelect<T extends boolean = true> {
  season?: T;
  type?: T;
  asOf?: T;
  entries?:
    | T
    | {
        rank?: T;
        player?: T;
        value?: T;
        valueLabel?: T;
        events?: T;
        previousRank?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rounds_select".
 */
export interface RoundsSelect<T extends boolean = true> {
  tournament?: T;
  number?: T;
  date?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores_select".
 */
export interface ScoresSelect<T extends boolean = true> {
  round?: T;
  player?: T;
  position?: T;
  positionTied?: T;
  toPar?: T;
  strokes?: T;
  thru?: T;
  today?: T;
  status?: T;
  cutProbability?: T;
  holeScores?:
    | T
    | {
        hole?: T;
        par?: T;
        strokes?: T;
        toPar?: T;
        result?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        drivingDistance?: T;
        fairwayHitRate?: T;
        greenInRegulation?: T;
        puttsPerRound?: T;
        sandSaveRate?: T;
        scrambleRate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  year?: T;
  name?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shots_select".
 */
export interface ShotsSelect<T extends boolean = true> {
  round?: T;
  player?: T;
  hole?: T;
  shotNo?: T;
  shotType?: T;
  club?: T;
  distanceYards?: T;
  carryYards?: T;
  startLocation?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  endLocation?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  startLie?: T;
  endLie?: T;
  remainingYards?: T;
  resultText?: T;
  aiCommentary?: T;
  aiCommentaryGenerated?: T;
  occurredAt?: T;
  trackman?:
    | T
    | {
        ballSpeed?: T;
        launchAngle?: T;
        spinRate?: T;
        apexHeight?: T;
      };
  video?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  tier?: T;
  contractFrom?: T;
  contractTo?: T;
  landingUrl?: T;
  adReportSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-orders_select".
 */
export interface TicketOrdersSelect<T extends boolean = true> {
  orderNo?: T;
  user?: T;
  ticketType?: T;
  quantity?: T;
  amount?: T;
  status?: T;
  paymentRef?: T;
  qrPayload?: T;
  purchasedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-types_select".
 */
export interface TicketTypesSelect<T extends boolean = true> {
  tournament?: T;
  name?: T;
  price?: T;
  validDate?: T;
  stock?: T;
  salesStart?: T;
  salesEnd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  season?: T;
  venue?: T;
  course?: T;
  startDate?: T;
  endDate?: T;
  prizeMoneyTotal?: T;
  status?: T;
  heroImage?: T;
  description?: T;
  pamphletPdf?: T;
  pamphletWebUrl?: T;
  officialStoreUrl?: T;
  ticketUrl?: T;
  cutLineAfterRound?: T;
  cutRule?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transport-infos_select".
 */
export interface TransportInfosSelect<T extends boolean = true> {
  tournament?: T;
  type?: T;
  name?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  timetable?:
    | T
    | {
        time?: T;
        note?: T;
        id?: T;
      };
  capacity?: T;
  occupancyStatus?: T;
  fee?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  sponsor?: T;
  displayName?: T;
  fullName?: T;
  birthYear?: T;
  gender?: T;
  postalCode?: T;
  prefecture?: T;
  address?: T;
  phone?: T;
  golfExperienceYears?: T;
  favoritePlayerText?: T;
  avatar?: T;
  snsAccounts?:
    | T
    | {
        provider?: T;
        accountId?: T;
        linkedAt?: T;
        id?: T;
      };
  golfClubSetting?:
    | T
    | {
        category?: T;
        brand?: T;
        model?: T;
        id?: T;
      };
  twoFactorEnabled?: T;
  twoFactorSecret?: T;
  twoFactorRecoveryCodes?: T;
  onboardingCompleted?: T;
  notificationMaster?: T;
  agreedTermsVersion?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-facilities_select".
 */
export interface VenueFacilitiesSelect<T extends boolean = true> {
  venue?: T;
  tournament?: T;
  type?: T;
  name?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  description?: T;
  photo?: T;
  menuItems?:
    | T
    | {
        name?: T;
        price?: T;
        photo?: T;
        id?: T;
      };
  openHours?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  address?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  accessTrain?: T;
  accessCar?: T;
  shuttleTimetable?:
    | T
    | {
        time?: T;
        from?: T;
        to?: T;
        note?: T;
        id?: T;
      };
  venueMapImage?: T;
  googleMapUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  file?: T;
  hlsUrl?: T;
  thumbnail?: T;
  durationSec?: T;
  orientation?: T;
  tournament?: T;
  round?: T;
  player?: T;
  hole?: T;
  shotNo?: T;
  shotTime?: T;
  shotType?: T;
  startLocation?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  endLocation?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  tags?: T;
  autoTagged?: T;
  publishedAt?: T;
  ogTitle?: T;
  ogImage?: T;
  shareUrl?: T;
  viewCount?: T;
  likeCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weather-forecasts_select".
 */
export interface WeatherForecastsSelect<T extends boolean = true> {
  tournament?: T;
  observedAt?: T;
  forecastFor?: T;
  condition?: T;
  temperature?: T;
  windSpeed?: T;
  windDirection?: T;
  precipProbability?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * 6-15 / 補-6-15-1。バージョンを更新すると再同意が必要になる（補-6-15-2）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents".
 */
export interface LegalDocument {
  id: number;
  /**
   * 6-15
   */
  terms?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 6-15
   */
  privacy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 補-6-15-2。`users.agreedTermsVersion` と突き合わせて再同意要否を判定する
   */
  version?: string | null;
  /**
   * 補-6-15-1
   */
  effectiveAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * アプリ起動時に取得される共通設定値
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings".
 */
export interface AppSetting {
  id: number;
  /**
   * ライブ系画面のポーリング間隔
   */
  liveScorePollIntervalSec: number;
  /**
   * 補-4-12-1。上限 10 名
   */
  favoritePlayerLimit: number;
  /**
   * これを下回る回線では低画質・軽量表示に切り替える
   */
  lowBandwidthThresholdKbps?: number | null;
  /**
   * オフライン時に表示するキャッシュの有効期限
   */
  offlineCacheTtlHours: number;
  /**
   * 補-4-15-1。1 ラウンドでこの通算スコア以下に到達した時点、または 1 ホールでイーグル以上を「好スコア」とする
   */
  goodScoreToPar: number;
  /**
   * ON の場合、アプリ側でメンテナンス画面を表示する
   */
  maintenanceMode?: boolean | null;
  /**
   * これ未満のバージョンでは強制アップデートを促す
   */
  minimumAppVersion?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents_select".
 */
export interface LegalDocumentsSelect<T extends boolean = true> {
  terms?: T;
  privacy?: T;
  version?: T;
  effectiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-settings_select".
 */
export interface AppSettingsSelect<T extends boolean = true> {
  liveScorePollIntervalSec?: T;
  favoritePlayerLimit?: T;
  lowBandwidthThresholdKbps?: T;
  offlineCacheTtlHours?: T;
  goodScoreToPar?: T;
  maintenanceMode?: T;
  minimumAppVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}